import { useRef, useEffect } from "react";
import Matter from "matter-js";                       // Import Matter.js library

export const useCarromPhysics = (screenRef , onScore , onQueenStatus) => {
  const engineRef = useRef(null);    // Reference to the Matter.js engine, allowing us to access and manipulate the physics simulation throughout the component's lifecycle.
  useEffect(() => {
    if (!screenRef.current) return;    // Check if the screen reference is available before proceeding with the physics setup. This ensures that we have a valid DOM element to render the physics simulation on, preventing any potential errors or issues that could arise from trying to access a null or undefined reference. By returning early if the screen reference is not available, we can ensure that the physics setup only occurs when we have a valid target for rendering the carrom game, allowing for a smoother and more reliable user experience.

    screenRef.current.innerHTML = '';   // Clear the inner HTML of the screen element to ensure that we have a clean slate for rendering the physics simulation. This step is important to prevent any existing content from interfering with the visual representation of the carrom game, allowing us to create a clear and focused gaming experience for players. By setting innerHTML to an empty string, we can ensure that the screen element is ready to display the carrom board and pieces without any distractions or visual clutter.

    const engine = Matter.Engine.create({
      enableSleeping: true,   // Enable sleeping in the physics engine to optimize performance by allowing bodies that are at rest to enter a sleep state, reducing unnecessary calculations and improving the overall efficiency of the simulation. This is particularly beneficial for a carrom game where many pieces may come to rest on the board, allowing the engine to focus its resources on active interactions and movements, enhancing the gameplay experience for players.
      positionIterations : 10,
      velocityIterations : 10
    });     // Create a new Matter.js engine to manage the physics simulation for the carrom game. The Matter.Engine.create() function initializes a new engine instance that will be responsible for calculating the physics interactions between the carrom pieces, walls, and pockets during gameplay. By creating an engine, we can simulate realistic movements and collisions based on the defined physics properties of the game elements, enhancing the overall gaming experience for players.  

    engineRef.current = engine;    // Store the engine reference in the engineRef to allow access to the physics simulation throughout the component's lifecycle. By assigning the created engine to engineRef.current, we can ensure that we have a persistent reference to the engine that can be used in other parts of the component, such as event handlers or cleanup functions, allowing us to manage and manipulate the physics simulation effectively during gameplay.
    engine.gravity.y = 0; // Disable gravity for a top-down view of the carrom board , Set the gravity of the engine to zero along the y-axis to create a top-down view of the carrom board. By setting engine.gravity.y to 0, we can prevent the carrom pieces from being affected by gravity, allowing them to move freely across the board without falling or being pulled downwards. This is important for creating a realistic and enjoyable carrom game experience, as it allows players to focus on the interactions between the pieces and the board without worrying about gravity affecting their movements during gameplay.

    const render = Matter.Render.create({         // Create a renderer to visualize the physics simulation. The Matter.Render.create() function initializes a new renderer instance that will be responsible for drawing the carrom board and pieces on the screen. By passing in the engine and the screen reference, we can link the renderer to our physics engine and specify where to render the simulation. This allows us to see the movements and interactions of the carrom pieces as they are simulated by the physics engine.
      element: screenRef.current,      // Specify the DOM element where the renderer will draw the simulation. By using screenRef.current, we can target the specific element in the DOM that we want to use for rendering the carrom game. This allows us to control where the visual representation of the physics simulation will be displayed on the screen.
      engine: engine,  // Link the renderer to the physics engine. By passing the engine reference to the renderer, we can ensure that the renderer is aware of the physics simulation and can accurately visualize the movements and interactions of the carrom pieces based on the physics calculations performed by the engine.
      options: {           // Set various options for the renderer to customize the appearance of the simulation. These options include:
        width: 600,
        height: 600,
        wireframes: false,     // Set wireframes to false to render solid shapes instead of wireframe outlines. This option allows us to create a more visually appealing representation of the carrom pieces and board, making it easier for players to see and interact with the game elements. By setting wireframes to false, we can enhance the overall visual experience of the carrom game.
        background: 'transparent',    // Set the background of the renderer to transparent to allow the underlying styles and colors of the screen element to show through. This option is important for creating a visually cohesive carrom game, as it allows us to maintain the aesthetic design of the game while still rendering the physics simulation on top. By using a transparent background, we can ensure that the carrom pieces and board are visually integrated with the overall design of the game, enhancing the player's immersion and enjoyment.


        pixelRatio: window.devicePixelRatio || 1  

          // Set the pixel ratio for the renderer to ensure that the simulation is rendered at the appropriate resolution based on the device's display capabilities. By using window.devicePixelRatio, we can automatically adjust the rendering quality for high-resolution displays, providing a sharper and clearer visual experience for players. If window.devicePixelRatio is not available, we default to a pixel ratio of 1 to ensure that the simulation is still rendered correctly on standard displays. By setting the pixel ratio, we can enhance the overall visual quality of the carrom game across different devices and screen resolutions.
      },
    });

    const wallOptions = {       // Define options for the walls of the carrom board. These options include:
      isStatic: true,      // Define options for the walls of the carrom board. By setting isStatic to true, we ensure that the walls will not move or be affected by forces in the physics simulation. This is important for creating a stable boundary for the carrom pieces to interact with, preventing them from falling off the board or moving outside of the designated play area. The wallOptions can be used when creating the walls of the carrom board to ensure they behave as intended in the physics simulation.

      render: { fillStyle: '#3e2723' },  // Set the fill style for the walls to a specific color (in this case, a dark brown). This option allows us to customize the appearance of the walls in the carrom game, making them visually distinct from the carrom pieces and enhancing the overall aesthetic of the game. By setting the fillStyle, we can create a more visually appealing and immersive carrom game environment.             Note :- works only when wireframes is set to false in the renderer options.

      restitution: 0.6  
    };

    const walls = [       // Create an array of walls for the carrom board. Each wall is defined using the Matter.Bodies.rectangle() function, which creates a rectangular body with specified position, dimensions, and options. The walls are positioned around the edges of the carrom board to create boundaries for the pieces to interact with during gameplay. By defining these walls with the appropriate options, we can ensure that they behave as intended in the physics simulation, providing a realistic and enjoyable gaming experience for players.

      Matter.Bodies.rectangle(300, -50, 800, 100, wallOptions),    // Create the top walls of the carrom board using Matter.Bodies.rectangle() function. Each wall is defined by its position (x and y coordinates), dimensions (width and height), and the wallOptions that we defined earlier. By creating these walls, we establish the boundaries of the carrom board, preventing the pieces from moving outside of the designated play area. The walls will interact with the carrom pieces based on the physics simulation, allowing for realistic collisions and bounces during gameplay.

      Matter.Bodies.rectangle(300, 650, 800, 100, wallOptions),  // Create the bottom wall of the carrom board with specified position, dimensions, and options. This wall will serve as the lower boundary of the play area, ensuring that the carrom pieces do not fall off the board during gameplay. By defining this wall with the appropriate options, we can control its behavior in the physics simulation, allowing for realistic interactions with the carrom pieces when they collide with it.

      Matter.Bodies.rectangle(-50, 300, 100, 800, wallOptions),  // Create the left wall of the carrom board  with specified position, dimensions, and options. This wall will serve as the left boundary of the play area, preventing the carrom pieces from moving outside of the designated area during gameplay. By defining this wall with the appropriate options, we can control its behavior in the physics simulation, allowing for realistic interactions with the carrom pieces when they collide with it.

      Matter.Bodies.rectangle(650, 300, 100, 800, wallOptions)       // Create the right wall of the carrom board with specified position, dimensions, and options. This wall will serve as the right boundary of the play area, ensuring that the carrom pieces do not move outside of the designated area during gameplay. By defining this wall with the appropriate options, we can control its behavior in the physics simulation, allowing for realistic interactions with the carrom pieces when they collide with it.

    ];

    const pocketpositions = [           // Define the positions of the pockets on the carrom board. Each pocket is represented by an object with x and y coordinates, indicating its location on the board. These positions will be used to determine when a carrom piece has been pocketed during gameplay, allowing us to update the game state accordingly. By defining these pocket positions, we can create a more engaging and interactive carrom game experience for players as they aim to pocket their pieces into these designated areas.

      { x : 35 , y : 35 },    // Define the positions of the pockets on the carrom board. Each pocket is represented by an object with x and y coordinates, indicating its location on the board. These positions will be used to determine when a carrom piece has been pocketed during gameplay, allowing us to update the game state accordingly. By defining these pocket positions, we can create a more engaging and interactive carrom game experience for players as they aim to pocket their pieces into these designated areas. ( this is top left pocket )
      { x : 565 , y : 35 } ,      // top right pocket
      { x : 35 , y : 565 } ,        // bottom left pocket
      { x : 565 , y : 565 }         // bottom right pocket
    ]

    const pockets = pocketpositions.map( pos =>             //  Create circular bodies to represent the pockets on the carrom board using Matter.Bodies.circle() function. Each pocket is defined by its position (x and y coordinates) and a radius of 25, along with options that specify its physical properties and appearance in the physics simulation. By creating these pocket bodies, we can detect when a carrom piece collides with a pocket during gameplay, allowing us to implement logic for pocketing pieces and updating the game state accordingly. The options for each pocket include:
      Matter.Bodies.circle(pos.x , pos.y , 25 , {                   // Create circular bodies to represent the pockets on the carrom board using Matter.Bodies.circle() function. Each pocket is defined by its position (x and y coordinates) and a radius of 25, along with options that specify its physical properties and appearance in the physics simulation. By creating these pocket bodies, we can detect when a carrom piece collides with a pocket during gameplay, allowing us to implement logic for pocketing pieces and updating the game state accordingly. The options for each pocket include:
        isStatic: true,                           // Set isStatic to true to ensure that the pocket bodies do not move or interact with other bodies in the physics simulation. This is important for creating a stable and consistent representation of the pockets on the carrom board, allowing us to accurately detect when a carrom piece collides with a pocket during gameplay. By setting isStatic to true, we can ensure that the pockets serve their intended purpose as stationary targets for players to aim for when trying to pocket their pieces.
        isSensor: true,                   // Set isSensor to true to make the pocket bodies act as sensors in the physics simulation. This means that they will not physically interact with other bodies, but they will still trigger collision events when a carrom piece collides with them. This is important for implementing the logic of pocketing pieces during gameplay, as it allows us to detect when a piece has been pocketed without affecting the movement or behavior of the pieces in the simulation. By setting isSensor to true, we can create a more realistic and functional representation of the pockets in the carrom game.
        render : { visible : false }                    // Set the render option to make the pocket bodies invisible in the visual representation of the carrom game. By setting visible to false, we can ensure that the pockets do not interfere with the visual aesthetics of the game while still allowing them to function as intended in the physics simulation. This allows players to focus on the carrom pieces and the board without being distracted by visible pocket bodies, creating a cleaner and more immersive gaming experience. By making the pockets invisible, we can enhance the overall visual appeal of the carrom game while maintaining their functionality in detecting when pieces are pocketed during gameplay.
      })
    );


    // coin spawn logic here
    const coins = [];                 // Initialize an empty array to hold the coin bodies that will be created for the carrom game. This array will be populated with the circular bodies representing the coins on the board, allowing us to manage and interact with them during gameplay. By using an array to store the coin bodies, we can easily access and manipulate them as needed, such as checking for collisions, updating their positions, or removing them from the board when they are pocketed. This structure helps us organize the coin bodies effectively within the physics simulation of the carrom game.
    const centerX = 300;        // Define the x-coordinate for the center of the carrom board, which will be used as a reference point for positioning the coins. By setting centerX to 300, we can ensure that the coins are arranged symmetrically around the center of the board, creating a visually balanced and appealing layout for the carrom game. This center point will serve as the basis for calculating the positions of the coins in both the inner and outer circles, allowing us to create a cohesive and organized arrangement of pieces on the board during gameplay.
    const centerY = 300;        // same as centerX but for y-coordinate, defining the vertical center of the carrom board for positioning the coins in a symmetrical arrangement around the center point during gameplay.
    const coinRadius = 15;          // Define the radius for the coins in the carrom game. By setting coinRadius to 15, we can ensure that the coins are appropriately sized for the game, allowing for realistic interactions and collisions with other pieces on the board. This radius will be used when creating the circular bodies for the coins, determining their size and how they will fit within the layout of the carrom board during gameplay. By choosing an appropriate coin radius, we can enhance the overall visual appeal and functionality of the carrom game, providing a more enjoyable experience for players.

    // the queen ( center )                300     300           15
    const createqueen = () => (Matter.Bodies.circle(centerX, centerY, coinRadius, {           // Create a circular body to represent the queen coin in the carrom game. The Matter.Bodies.circle() function is used to create a circular body with specified position (centerX and centerY), radius (coinRadius), and options that define its physical properties and appearance in the physics simulation. By creating the queen coin with these properties, we can ensure that it interacts realistically with the other pieces on the carrom board during gameplay, adding an important element to the game as players aim to pocket the queen for additional points. The options for the queen coin include:

      label : 'queen',       // Set the label of the queen coin body to 'queen' to identify it in the physics simulation. This label can be used to differentiate the queen coin from other bodies in the simulation, allowing us to apply specific logic or interactions when the queen coin collides with other pieces or pockets on the board during gameplay. By assigning a label to the queen coin, we can enhance the functionality and interactivity of the carrom game.

      restitution: 0.4,         // Set restitution to 0.4 to make the queen coin moderately bouncy, allowing it to bounce off other pieces and walls with some elasticity. This option enhances the gameplay experience by adding a realistic bounce effect when the queen coin collides with other elements on the board, making the game more dynamic and enjoyable for players. By adjusting the restitution value, we can control how much energy is retained during collisions, creating a more engaging and interactive carrom game.
      frictionAir: 0.04,        // Set frictionAir to 0.04 to provide a moderate amount of air resistance for the queen coin, allowing it to slow down gradually as it moves across the board. This option adds a layer of realism to the physics simulation, as it simulates the effect of air resistance on the movement of the coin, making the gameplay experience more immersive and enjoyable for players. By adjusting the frictionAir value, we can control how quickly the queen coin slows down, creating a more engaging and interactive carrom game.
      render: {
        fillStyle: "#ef4444"              //  Set the fill style for the queen coin to a specific color (in this case, a bright red). This option allows us to customize the appearance of the queen coin in the carrom game, making it visually distinct from the other coins and enhancing the overall aesthetic of the game. By setting the fillStyle, we can create a more visually appealing and immersive carrom game environment, allowing players to easily identify and focus on the queen coin during gameplay. Note :- works only when wireframes is set to false in the renderer options.
        //  strokeStyle : " b91c1c" , lineWidth : 2
      }
    }));

    let queen = createqueen();   // Store the created queen coin body in a variable called queen to allow for easy reference and manipulation throughout the component. By assigning the created queen coin to the variable queen, we can easily access its properties and methods when needed, such as checking for collisions, updating its position, or removing it from the board when it is pocketed during gameplay. This variable serves as a convenient way to manage the queen coin within the physics simulation of the carrom game, enhancing our ability to implement game logic and interactions involving the queen coin effectively.

    
    // inner circle ( 6 coins )
    for (let i = 0; i < 6; i++) {         // Create a loop to generate the inner circle of coins around the queen coin. The loop iterates 6 times, creating 6 coins that are evenly spaced around the center of the board. The position of each coin is calculated using trigonometric functions (cosine and sine) to determine their x and y coordinates based on their angle from the center. By creating these coins with the specified properties, we can ensure that they interact realistically with the other pieces on the carrom board during gameplay, adding an important element to the game as players aim to pocket these coins for points.
      const angle = (i * Math.PI) / 3;            // Calculate the angle for each coin based on its position in the loop. By multiplying the loop index (i) by Math.PI and dividing by 3, we can determine the angle at which each coin will be placed around the center of the board. This calculation ensures that the coins are evenly spaced in a circular pattern around the queen coin, creating a visually appealing and balanced arrangement for the inner circle of coins in the carrom game.
      const x = centerX + Math.cos(angle) * (coinRadius * 2.1);             // Calculate the x-coordinate for each coin based on its angle and distance from the center. By using the cosine function, we can determine how far along the x-axis each coin should be placed from the center of the board, creating a circular arrangement around the queen coin. The distance is determined by multiplying the coinRadius by 2.1, which provides enough space between the coins to prevent them from overlapping while still maintaining a visually appealing layout for the inner circle of coins in the carrom game.
      const y = centerY + Math.sin(angle) * (coinRadius * 2.1);            // Calculate the y-coordinate for each coin based on its angle and distance from the center. By using the sine function, we can determine how far along the y-axis each coin should be placed from the center of the board, creating a circular arrangement around the queen coin. The distance is determined by multiplying the coinRadius by 2.1, which provides enough space between the coins to prevent them from overlapping while still maintaining a visually appealing layout for the inner circle of coins in the carrom game.
      // const color = i % 2 === 0 ? "#ffffff" : "#262626";
      coins.push(Matter.Bodies.circle(              // Create a circular body for each coin in the inner circle using Matter.Bodies.circle() function. Each coin is defined by its calculated x and y coordinates, radius (coinRadius), and options that specify its physical properties and appearance in the physics simulation. By creating these coins with the appropriate properties, we can ensure that they interact realistically with the other pieces on the carrom board during gameplay, adding an important element to the game as players aim to pocket these coins for points. The options for each coin include:
        x, y, coinRadius, {
        restitution: 0.4,     // Set restitution to 0.4 to make the coins moderately bouncy, allowing them to bounce off other pieces and walls with some elasticity. This option enhances the gameplay experience by adding a realistic bounce effect when the coins collide with other elements on the board, making the game more dynamic and enjoyable for players. By adjusting the restitution value, we can control how much energy is retained during collisions, creating a more engaging and interactive carrom game.
        frictionAir: 0.04,    // Set frictionAir to 0.04 to provide a moderate amount of air resistance for the coins, allowing them to slow down gradually as they move across the board. This option adds a layer of realism to the physics simulation, as it simulates the effect of air resistance on the movement of the coins, making the gameplay experience more immersive and enjoyable for players. By adjusting the frictionAir value, we can control how quickly the coins slow down, creating a more engaging and interactive carrom game.
        friction: 0.02,       // Set friction to 0.02 to provide a small amount of surface friction for the coins, allowing them to interact with the board and other pieces in a more realistic manner. This option helps to prevent the coins from sliding indefinitely across the board, adding a sense of realism to the physics simulation and enhancing the overall gameplay experience for players. By adjusting the friction value, we can control how much resistance the coins encounter when moving across the board, creating a more engaging and interactive carrom game.
        slop: 0.01,  // Set slop to 0.01 to allow for a small amount of penetration between the coins and other bodies in the physics simulation. This option helps to prevent issues with collision detection, such as coins getting stuck or jittering when they come into contact with other pieces or walls on the board. By allowing a small amount of slop, we can ensure smoother interactions between the coins and other elements in the carrom game, enhancing the overall gameplay experience for players.
        label :'coin',     // Set the label of each coin body to 'coin' to identify them in the physics simulation. This label can be used to differentiate the coins from other bodies in the simulation, allowing us to apply specific logic or interactions when the coins collide with other pieces or pockets on the board during gameplay. By assigning a label to each coin, we can enhance the functionality and interactivity of the carrom game.
        render: { fillStyle: i % 2 === 0 ? "#ffffff" : "#262626" }
      }
      ));
    }

    // outer circle ( 12 coins )                  same comments for the loop as above but with 12 iterations and adjusted angle calculation to space the coins evenly around the center of the board, creating a larger circular arrangement for the outer circle of coins in the carrom game.
    for (let i = 0; i < 12; i++) {
      const angle = (i * Math.PI) / 6;
      const x = centerX + Math.cos(angle) * (coinRadius * 4.1);
      const y = centerY + Math.sin(angle) * (coinRadius * 4.1);
      // const color = i % 2 === 0 ? "#ffffff" : "#262626";
      coins.push(Matter.Bodies.circle(
        x, y, coinRadius, {
        restitution: 0.4,
        frictionAir: 0.04,
        friction: 0.02,
        slop: 0.01,
        label :'coin',
        render: { fillStyle: i % 2 === 0 ? "#ffffff" : "#262626" }
      }
      ));
    }

    const striker = Matter.Bodies.circle(300, 480, 25, { // Create a circular body to represent the striker in the carrom game. The Matter.Bodies.circle() function is used to create a circular body with specified position (x and y coordinates), radius, and options. The options include properties such as mass, restitution, frictionAir, and render settings that define the physical behavior and appearance of the striker in the physics simulation. By creating the striker with these properties, we can ensure that it interacts realistically with the other pieces on the carrom board during gameplay.
      label : 'striker',      // Set the label of the striker body to 'striker' to identify it in the physics simulation. This label can be used to differentiate the striker from other bodies in the simulation, allowing us to apply specific logic or interactions when the striker collides with other pieces or pockets on the board during gameplay. By assigning a label to the striker, we can enhance the functionality and interactivity of the carrom game.
      mass: 5,       // Higher mass → hits harder, Lower mass → moves easily
     //  restitution: 0.5,        // Higher restitution → bouncier, Lower restitution → less bouncy
      frictionAir: 0.04,       // Higher frictionAir → slows down faster, Lower frictionAir → retains speed longer
      render: { fillStyle: '#ffeb3b', strokeStyle: '#fbc02d', lineWidth: 4 } // Set the fill style, stroke style, and line width for the striker to customize its appearance in the carrom game. The fillStyle defines the color used to fill the striker, while the strokeStyle specifies the color of the outline around the striker. The LineWidth option determines the thickness of the outline. By setting these render options, we can create a visually distinct and appealing striker that stands out on the carrom board, enhancing the overall aesthetic of the game.


      // note :- the render options for the striker will only work if wireframes is set to false in the renderer options, allowing us to see the custom colors and styles applied to the striker in the visual representation of the carrom game.
    });
    const mouse = Matter.Mouse.create(render.canvas);       // Create a mouse input for the renderer's canvas to enable user interaction with the carrom pieces. The Matter.Mouse.create() function initializes a new mouse instance that is linked to the canvas element used by the renderer. This allows us to track mouse movements and clicks on the canvas, enabling players to interact with the carrom pieces by clicking and dragging them to simulate shooting the striker or moving the coins on the board. By creating a mouse input, we can enhance the interactivity of the carrom game and provide a more engaging gaming experience for players.
    const mouseConstraint = Matter.MouseConstraint.create(engine, {          // Create a mouse constraint to allow the user to interact with the carrom pieces using the mouse input. The Matter.MouseConstraint.create() function initializes a new mouse constraint that is linked to the physics engine and the mouse input. This constraint allows players to click and drag the carrom pieces on the board, simulating the action of shooting the striker or moving the coins during gameplay. By creating a mouse constraint, we can enable intuitive and interactive controls for the carrom game, enhancing the overall user experience and making it more enjoyable for players. The options for the mouse constraint include:
      mouse: mouse,            // Link the mouse input to the mouse constraint to enable user interaction with the carrom pieces. By passing the mouse instance to the mouse constraint, we can ensure that the constraint responds to mouse movements and clicks, allowing players to click and drag the carrom pieces on the board during gameplay. This connection between the mouse input and the mouse constraint is essential for creating an interactive and engaging carrom game experience for players.
      constraint: { stiffness: 0.1, render: { visible: false } }        // Set the stiffness of the mouse constraint to control how tightly it holds the carrom pieces when they are clicked and dragged. A lower stiffness value will allow for more flexible movement, while a higher stiffness value will create a stronger hold on the pieces. Additionally, we set the render option to make the constraint invisible, ensuring that it does not interfere with the visual representation of the carrom game while still allowing for effective user interaction with the pieces on the board.
    });
    render.mouse = mouse;              // Link the mouse input to the renderer to ensure that mouse interactions are properly captured and processed during the physics simulation. By assigning the mouse instance to the render.mouse property, we can enable the renderer to track mouse movements and clicks on the canvas, allowing for seamless user interaction with the carrom pieces during gameplay. This connection between the mouse input and the renderer is essential for creating an interactive and engaging carrom game experience for players.

    Matter.Composite.add(engine.world, [...walls, striker, ...coins, mouseConstraint , ...pockets , queen]); // Add all the created bodies (walls, striker, coins, mouse constraint, pockets, and queen) to the physics engine's world using Matter.Composite.add(). This function takes the engine's world as the first argument and an array of bodies to be added as the second argument. By adding these bodies to the world, we can ensure that they are included in the physics simulation and will interact with each other according to the defined properties and behaviors during gameplay. This step is crucial for setting up the carrom game environment and enabling realistic interactions between the pieces on the board.


    Matter.Events.on(engine , 'collisionStart' , (event) => {       // Set up an event listener for collision events in the physics engine. By using Matter.Events.on(), we can listen for the 'collisionStart' event, which is triggered whenever a collision occurs between bodies in the physics simulation. The callback function receives an event object that contains information about the collision, including the pairs of bodies that collided. This allows us to implement custom logic to handle specific interactions during gameplay, such as detecting when a coin has been pocketed or when the striker collides with other pieces on the board, enhancing the overall interactivity and functionality of the carrom game.
      event.pairs.forEach((pair) => {               // Iterate through each pair of bodies that collided during the 'collisionStart' event. The event.pairs array contains information about all the collisions that occurred, and by using forEach, we can process each collision pair individually. This allows us to implement specific logic for each collision, such as checking if a coin has been pocketed or if the striker has collided with other pieces on the board, enabling us to update the game state accordingly and enhance the overall gameplay experience in the carrom game.

        const{ bodyA , bodyB } = pair ;             // Destructure the bodyA and bodyB properties from the collision pair to access the two bodies that were involved in the collision. By extracting these properties, we can easily reference the specific bodies that collided and implement custom logic based on their labels or other properties during the 'collisionStart' event. This allows us to determine if a coin has been pocketed or if the striker has collided with other pieces on the board, enabling us to update the game state and enhance the overall interactivity of the carrom game.

        const isPocket = pockets.includes(bodyA) || pockets.includes(bodyB); // declaration                           == can be true or false       // Check if either of the colliding bodies is a pocket by using the includes() method to see if bodyA or bodyB is present in the pockets array. This allows us to determine if a collision involves a pocket, which is important for implementing game logic related to pocketing coins during gameplay. By checking if either body is a pocket, we can execute specific actions, such as removing a coin from the board or resetting the striker's position when it collides with a pocket, enhancing the overall functionality and interactivity of the carrom game.

        const otherBody = pockets.includes( bodyA ) ? bodyB : bodyA ;    // declaration              == can be bodyA or bodyB depending on which one is the pocket       // Determine which of the colliding bodies is the non-pocket body by checking if bodyA is a pocket. If bodyA is a pocket, then otherBody will be set to bodyB; otherwise, it will be set to bodyA. This allows us to identify the specific body that collided with the pocket, which is important for implementing game logic related to pocketing coins during gameplay. By determining the otherBody, we can execute specific actions based on its properties, such as removing a coin from the board or resetting the striker's position when it collides with a pocket, enhancing the overall functionality and interactivity of the carrom game.

        if(isPocket){             //  Check if the collision involves a pocket by evaluating the isPocket variable. If isPocket is true, it means that one of the colliding bodies is a pocket, and we can proceed to implement the logic for handling the collision with the pocket. This may include actions such as removing a coin from the board if it was pocketed or resetting the striker's position if it collided with a pocket, enhancing the overall gameplay experience in the carrom game.    

          if(otherBody.label === 'striker'){                // Check if the other body involved in the collision is the striker by evaluating its label property. If otherBody.label is equal to 'striker', it means that the striker has collided with a pocket, and we can implement specific logic to handle this scenario. This may include resetting the striker's position to a default location on the board and setting its velocity to zero to stop its movement, allowing players to continue playing without any disruption caused by the striker being pocketed. By handling this case separately, we can ensure that the game remains enjoyable and functional even when the striker interacts with the pockets on the board.
            Matter.Body.setPosition(otherBody ,{x : 300 , y : 480});          // Reset the position of the striker to a default location on the board (x: 300, y: 480) when it collides with a pocket. This allows players to continue playing without any disruption caused by the striker being pocketed, ensuring that the game remains enjoyable and functional even when the striker interacts with the pockets on the board. By setting the position of the striker back to its starting point, we can maintain a smooth gameplay experience for players as they aim to shoot the striker and pocket coins during the carrom game.
            Matter.Body.setVelocity(otherBody ,{x : 0 , y : 0});                        // Set the velocity of the striker to zero when it collides with a pocket. This ensures that the striker stops moving immediately after being reset to its default position, preventing any unintended movement or interactions that could occur if the striker retained its velocity after being pocketed. By setting the velocity to zero, we can maintain a smooth and controlled gameplay experience for players as they continue to play the carrom game after the striker interacts with the pockets on the board.
          }else{
            const type = otherBody.label ;          // Get the label of the other body involved in the collision to determine its type (e.g., 'coin' or 'queen'). This allows us to implement specific logic based on the type of body that collided with the pocket, such as removing a coin from the board if it was pocketed or updating the game state if the queen was pocketed, enhancing the overall functionality and interactivity of the carrom game.

            Matter.Composite.remove(engine.world , otherBody);            // Remove the other body (which is not the striker) from the physics engine's world when it collides with a pocket. This is typically done when a coin is pocketed during gameplay, allowing us to visually remove the coin from the board and update the game state accordingly. By removing the body from the engine's world, we can ensure that it no longer interacts with other pieces on the board, creating a more realistic and enjoyable gaming experience for players as they aim to pocket coins during the carrom game.
            console.log(" Goal ! coin packed ");
            onScore(type);         // Call the onScore function with the type of the body that was pocketed (e.g., 'coin' or 'queen') to update the game state and score accordingly. This allows us to keep track of the player's progress and provide feedback based on their actions during gameplay, enhancing the overall interactivity and enjoyment of the carrom game. By passing the type of the pocketed body to the onScore function, we can implement specific logic for updating scores, checking for win conditions, or providing visual feedback to players as they play the game.
          }
        }
      });
    });

    window.respawnQueen = () => {
      const newQueen = createqueen();
      Matter.Composites.add(engine.world , newQueen);
    };

    const runner = Matter.Runner.create();      // Create a runner to control the update loop of the physics simulation. The Matter.Runner.create() function initializes a new runner instance that will be responsible for continuously updating the physics engine and rendering the simulation. By using a runner, we can ensure that the physics simulation runs smoothly and consistently, allowing for real-time interactions and movements of the carrom pieces on the board. The runner will call the necessary functions to update the physics engine and render the changes on the screen, creating an immersive and interactive carrom game experience.

    Matter.Runner.run(runner, engine);    // Start the runner to begin the physics simulation. By calling Matter.Runner.run() with the runner's engine, we initiate the continuous update loop of the physics simulation. This allows the engine to calculate the movements and interactions of the carrom pieces based on the defined physics properties and rules. As a result, players can see the pieces move and interact in real-time as they play the carrom game, creating an engaging and dynamic gaming experience.

    Matter.Render.run(render);          // Start the renderer to visualize the physics simulation. By calling Matter.Render.run() with the render instance, we begin the process of drawing the carrom board and pieces on the screen based on the current state of the physics simulation. This allows players to see the movements and interactions of the carrom pieces in real-time as they play the game, enhancing the overall visual experience and immersion in the carrom game environment.

    return () => {
      Matter.Render.stop(render);         // Stop the renderer when the component is unmounted or when the effect is cleaned up. This ensures that the rendering process is properly terminated, preventing any potential memory leaks or performance issues that could arise from an active renderer running in the background after the component has been removed from the DOM. By calling Matter.Render.stop(), we can clean up the resources used by the renderer and ensure that it does not continue to run unnecessarily, allowing for better performance and resource management in the application.
      Matter.Runner.stop(runner);             // Stop the runner to halt the physics simulation when the component is unmounted or when the effect is cleaned up. This ensures that the physics engine is properly terminated, preventing any potential memory leaks or performance issues that could arise from an active runner running in the background after the component has been removed from the DOM. By calling Matter.Runner.stop(), we can clean up the resources used by the runner and ensure that it does not continue to run unnecessarily, allowing for better performance and resource management in the application.
      Matter.Engine.clear(engine);            // Clear the physics engine to reset its state and free up resources when the component is unmounted or when the effect is cleaned up. This ensures that any bodies, constraints, or other elements added to the engine are removed, preventing potential memory leaks and ensuring that the engine is ready for a fresh start if the component is remounted. By calling Matter.Engine.clear(), we can maintain optimal performance and resource management in the application by properly cleaning up the physics engine when it is no longer needed.
      Matter.World.clear(engine.world);           // Clear the physics world to remove all bodies, constraints, and other elements from the simulation when the component is unmounted or when the effect is cleaned up. This ensures that the physics world is reset to an empty state, preventing any potential memory leaks or performance issues that could arise from lingering elements in the world after the component has been removed from the DOM. By calling Matter.World.clear(), we can maintain optimal performance and resource management in the application by properly cleaning up the physics world when it is no longer needed.
      render.canvas.remove();           // remove all the canvas  elements created by the renderer to free up resources and prevent memory leaks when the component is unmounted or when the effect is cleaned up. This ensures that any canvas elements used for rendering the physics simulation are properly removed from the DOM, allowing for better performance and resource management in the application. By calling render.canvas.remove(), we can ensure that the visual elements associated with the renderer are cleaned up effectively when they are no longer needed.
      render.canvas = null;               // Clear the reference to the canvas element in the renderer to prevent any potential memory leaks or issues with lingering references when the component is unmounted or when the effect is cleaned up. By setting render.canvas to null, we can ensure that any references to the canvas element are properly cleared, allowing for better performance and resource management in the application. This is an important step in the cleanup process to ensure that all resources associated with the renderer are properly released when they are no longer needed.
      render.context = null;                          // Clear the reference to the rendering context in the renderer 
      render.textures = {};                             // Clear the textures used by the renderer to free up resources and prevent memory leaks when the component is unmounted or when the effect is cleaned up. By setting render.textures to an empty object, we can ensure that any textures used for rendering the physics simulation are properly cleared, allowing for better performance and resource management in the application. This step is crucial in the cleanup process to ensure that all resources associated with the renderer are effectively released when they are no longer needed. By clearing the textures, we can prevent any potential issues that could arise from lingering texture references in the renderer after the component has been removed from the DOM, ensuring optimal performance and resource management in the application.
    };
  }, [screenRef]);                        // The dependency array [screenRef] ensures that the effect runs whenever the screenRef changes, allowing us to set up the physics simulation correctly based on the current reference to the screen element.

  return engineRef.current;                     // Return the current value of the engine reference, allowing other components or functions to access and interact with the physics engine as needed. By returning engineRef.current, we can provide access to the initialized physics engine instance, enabling other parts of the application to utilize its functionality for managing the carrom game simulation, such as applying forces, handling collisions, or updating the state of the game based on user interactions or game events.
}
